name = "OscillatoryIntegrals"
uuid = "36d79ec0-be04-40c6-b002-a7ecbe3190c2"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.0.1"

[deps]
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ApproxFun = "0.11"
SpecialFunctions = "0.10"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
